manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cfergeau
      url-base: https://github.com/cfergeau
    - name: NuclearSquid
      url-base: https://github.com/Nuclear-Squid
    - name: infely                           
      url-base: https://github.com/infely 
    - name: duckyb
      url-base: https://github.com/duckyb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-keyboard-quacken
      remote: cfergeau
      revision: zmk-main
    - name: zmk-config-totem
      remote: cfergeau
      revision: zmk-module
    - name: zmk-new_corne
      url: https://github.com/a741725193/zmk-new_corne
      revision: main
    - name: nice-view-battery                  
      remote: infely                          
      revision: main
    - name: urchin-zmk-module
      remote: duckyb
      revision: main
  self:
    path: config
